### ISSUE TITLE
리팩토링 (폴더 구조, 에러 핸들러)

### ISSUE THREAD

**Issue by SuHyeon00** [EWHA-Inkspire/inkspire-BE#56]
### TODO
- [ ] 디렉토리 구조 도메인 별로 관리하도록 수정
- [ ] 응답 코드 형태 및 반환 상태 응답 DTO에서 갖고오도록 수정
- [ ] 전역 에러 핸들러 추가
